# Generated by Django 5.2.12 on 2026-06-17 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0007_remove_user_department_user_departments"),
        ("contacts", "0005_contactremark"),
        ("crm", "0017_stage_crm_stage_pipeline_order_idx"),
        ("hr", "0003_alter_compliancecalendarentry_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesProgramme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "target_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "programme_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_programmes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sales_programmes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Programme",
                "verbose_name_plural": "Sales Programmes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("target_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("REVENUE_GATE", "Revenue Gate"),
                            ("CLOSE_DATE", "Close Date"),
                            ("ACTIVITY_TARGET", "Activity Target"),
                            ("TEAM_BUILDING", "Team Building"),
                            ("PRODUCT_LAUNCH", "Product Launch"),
                            ("TRAINING", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ACHIEVED", "Achieved"),
                            ("MISSED", "Missed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="sales_task_manager.salesprogramme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Milestone",
                "verbose_name_plural": "Programme Milestones",
                "ordering": ["target_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee_type",
                    models.CharField(
                        choices=[
                            ("USER", "Individual"),
                            ("TEAM", "Team"),
                            ("DEPARTMENT", "Department"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "achieved_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "weighted_progress_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ACHIEVED", "Achieved"),
                            ("EXCEEDED", "Exceeded"),
                            ("MISSED", "Missed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "new_business_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "renewal_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "upsell_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_targets",
                        to="authentication.department",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Target",
                "verbose_name_plural": "Sales Targets",
            },
        ),
        migrations.AddField(
            model_name="salesprogramme",
            name="sales_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="sales_task_manager.salestarget",
            ),
        ),
        migrations.CreateModel(
            name="SalesTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("MEETING", "Meeting"),
                            ("DEMO", "Demo"),
                            ("PROPOSAL", "Proposal"),
                            ("QUOTE", "Quote"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("EMAIL", "Email"),
                            ("RESEARCH", "Research"),
                            ("NEGOTIATION", "Negotiation"),
                            ("CONTRACT_REVIEW", "Contract Review"),
                            ("INTERNAL_REVIEW", "Internal Review"),
                            ("CLOSING", "Closing"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BACKLOG", "Backlog"),
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("IN_REVIEW", "In Review"),
                            ("DONE", "Done"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated revenue impact if this task is completed",
                        max_digits=15,
                    ),
                ),
                (
                    "weight_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Relative weight for progress calculation (0-100%)",
                        max_digits=5,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if created automatically by target engine",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_tasks",
                        to="contacts.contact",
                    ),
                ),
                (
                    "crm_deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_tasks",
                        to="crm.crm",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sales_task_manager.salesprogramme",
                    ),
                ),
                (
                    "sales_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="sales_task_manager.salestarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Task",
                "verbose_name_plural": "Sales Tasks",
                "ordering": ["order", "due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesTaskLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_REASSIGNED", "Task Reassigned"),
                            ("TASK_STATUS_CHANGED", "Task Status Changed"),
                            ("TASK_DUE_DATE_CHANGED", "Task Due Date Changed"),
                            ("TASK_PRIORITY_CHANGED", "Task Priority Changed"),
                            ("TARGET_CREATED", "Target Created"),
                            ("TARGET_UPDATED", "Target Updated"),
                            ("TARGET_ACHIEVED", "Target Achieved"),
                            ("MILESTONE_ACHIEVED", "Milestone Achieved"),
                            ("PROGRAMME_STATUS_CHANGED", "Programme Status Changed"),
                            ("COMMENT_ADDED", "Comment Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "sales_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sales_task_manager.salestarget",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sales_task_manager.salestask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Activity Log",
                "verbose_name_plural": "Task Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TargetAssignmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("TARGET_CREATED", "On Target Creation"),
                            ("DEAL_STAGE_CHANGE", "On Deal Stage Change"),
                            ("DEAL_CREATED", "On Deal Created"),
                            ("WEEKLY", "Weekly Recurring"),
                            ("MONTHLY", "Monthly Recurring"),
                            ("MANUAL", "Manual Only"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("MEETING", "Meeting"),
                            ("DEMO", "Demo"),
                            ("PROPOSAL", "Proposal"),
                            ("QUOTE", "Quote"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("EMAIL", "Email"),
                            ("RESEARCH", "Research"),
                            ("NEGOTIATION", "Negotiation"),
                            ("CONTRACT_REVIEW", "Contract Review"),
                            ("INTERNAL_REVIEW", "Internal Review"),
                            ("CLOSING", "Closing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "task_title_template",
                    models.CharField(
                        help_text="Use {{deal_name}}, {{contact_name}}, {{target_amount}} as variables",
                        max_length=255,
                    ),
                ),
                ("task_description_template", models.TextField(blank=True)),
                (
                    "due_date_offset_days",
                    models.IntegerField(
                        default=7, help_text="Days from trigger date to set as due date"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("DEAL_OWNER", "Deal Owner"),
                            ("TARGET_OWNER", "Target Owner"),
                            ("LEAST_LOADED", "Least Loaded"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("MANAGER", "Manager"),
                        ],
                        default="TARGET_OWNER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sales_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_rules",
                        to="sales_task_manager.salestarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Rule",
                "verbose_name_plural": "Assignment Rules",
            },
        ),
        migrations.CreateModel(
            name="TargetCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("QUARTERLY", "Quarterly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_revenue_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("task_auto_generation_enabled", models.BooleanField(default=True)),
                ("sprint_duration_days", models.IntegerField(default=14)),
                (
                    "appraisal_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_cycles",
                        to="hr.appraisalcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Cycle",
                "verbose_name_plural": "Target Cycles",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="salestarget",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_targets",
                to="sales_task_manager.targetcycle",
            ),
        ),
        migrations.AddField(
            model_name="salesprogramme",
            name="target_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programmes",
                to="sales_task_manager.targetcycle",
            ),
        ),
        migrations.CreateModel(
            name="TargetLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("expected_close_date", models.DateField()),
                (
                    "line_item_type",
                    models.CharField(
                        choices=[
                            ("NEW_BUSINESS", "New Business"),
                            ("RENEWAL", "Renewal"),
                            ("UPSELL", "Upsell"),
                            ("EXPANSION", "Expansion"),
                        ],
                        default="NEW_BUSINESS",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.CharField(
                        choices=[
                            ("LOW", "Low (<25%)"),
                            ("MEDIUM", "Medium (25-50%)"),
                            ("HIGH", "High (50-75%)"),
                            ("COMMITTED", "Committed (>75%)"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("is_attained", models.BooleanField(default=False)),
                ("attained_date", models.DateField(blank=True, null=True)),
                (
                    "actual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "crm_deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_line_items",
                        to="crm.crm",
                    ),
                ),
                (
                    "sales_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="sales_task_manager.salestarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Line Item",
                "verbose_name_plural": "Target Line Items",
                "ordering": ["expected_close_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="task_attachments/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sales_task_manager.salestask",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Attachment",
                "verbose_name_plural": "Task Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("FINISH_TO_START", "Finish → Start"),
                            ("START_TO_START", "Start → Start"),
                            ("FINISH_TO_FINISH", "Finish → Finish"),
                            ("START_TO_FINISH", "Start → Finish"),
                        ],
                        default="FINISH_TO_START",
                        max_length=20,
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_tasks",
                        to="sales_task_manager.salestask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="sales_task_manager.salestask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Dependency",
                "verbose_name_plural": "Task Dependencies",
            },
        ),
        migrations.CreateModel(
            name="TaskTimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="sales_task_manager.salestask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Time Log",
                "verbose_name_plural": "Task Time Logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeResourceAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of user's time allocated (e.g., 50.00 = 50%)",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Programme Lead"),
                            ("SDR", "SDR"),
                            ("AE", "Account Executive"),
                            ("SE", "Solutions Engineer"),
                            ("CSM", "Customer Success"),
                            ("MANAGER", "Manager"),
                            ("SUPPORT", "Support"),
                        ],
                        default="AE",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="sales_task_manager.salesprogramme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Allocation",
                "verbose_name_plural": "Resource Allocations",
                "unique_together": {("programme", "user", "start_date")},
            },
        ),
        migrations.AddIndex(
            model_name="salestask",
            index=models.Index(
                fields=["programme", "status"], name="sales_task__program_ba1c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestask",
            index=models.Index(
                fields=["assigned_to", "status"], name="sales_task__assigne_b95e93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestask",
            index=models.Index(
                fields=["crm_deal"], name="sales_task__crm_dea_907205_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestask",
            index=models.Index(
                fields=["due_date"], name="sales_task__due_dat_6b1701_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestask",
            index=models.Index(
                fields=["sales_target"], name="sales_task__sales_t_6c4b27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestasklog",
            index=models.Index(
                fields=["task", "created_at"], name="sales_task__task_id_84e1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestasklog",
            index=models.Index(
                fields=["sales_target", "created_at"],
                name="sales_task__sales_t_7d63b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salestarget",
            index=models.Index(
                fields=["cycle", "assigned_user"], name="sales_task__cycle_i_c58195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salestarget",
            index=models.Index(
                fields=["cycle", "assigned_department"],
                name="sales_task__cycle_i_acb37e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salestarget",
            index=models.Index(fields=["status"], name="sales_task__status_2a4187_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="salestarget",
            unique_together={
                ("cycle", "assignee_type", "assigned_user", "assigned_department")
            },
        ),
        migrations.AddIndex(
            model_name="salesprogramme",
            index=models.Index(
                fields=["target_cycle", "status"], name="sales_task__target__4cc8ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesprogramme",
            index=models.Index(
                fields=["priority", "status"], name="sales_task__priorit_e907d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskdependency",
            unique_together={("task", "depends_on")},
        ),
    ]
