# Generated by Django 5.2.12 on 2026-06-01 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "wage_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=21000.0,
                        help_text="Salary ceiling for bonus eligibility (Payment of Bonus Act)",
                        max_digits=15,
                    ),
                ),
                (
                    "minimum_bonus_pct",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "maximum_bonus_pct",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "allocable_surplus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Allocable surplus for the year",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bonus Configuration",
                "verbose_name_plural": "Bonus Configurations",
            },
        ),
        migrations.CreateModel(
            name="ESIConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_contribution_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.75,
                        help_text="Employee ESI contribution % of gross salary",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_contribution_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.25,
                        help_text="Employer ESI contribution % of gross salary",
                        max_digits=5,
                    ),
                ),
                (
                    "wage_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=21000.0,
                        help_text="Gross salary ceiling for ESI eligibility",
                        max_digits=15,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ESI Configuration",
                "verbose_name_plural": "ESI Configurations",
            },
        ),
        migrations.CreateModel(
            name="GratuityConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "formula_numerator",
                    models.IntegerField(
                        default=15,
                        help_text="Number of days salary per year of service (15 as per Act)",
                    ),
                ),
                (
                    "formula_denominator",
                    models.IntegerField(
                        default=26, help_text="Days in a month (26 as per standard)"
                    ),
                ),
                (
                    "min_service_years",
                    models.IntegerField(
                        default=5,
                        help_text="Minimum years of service for gratuity eligibility",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gratuity Configuration",
                "verbose_name_plural": "Gratuity Configurations",
            },
        ),
        migrations.CreateModel(
            name="PFConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_contribution_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="Employee PF contribution % of Basic+DA",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_epf_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.67,
                        help_text="Employer EPF contribution % of Basic+DA",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_eps_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.33,
                        help_text="Employer EPS contribution % of Basic+DA",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_edli_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="EDLI contribution % of Basic+DA",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_admin_charges_pct",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
                ),
                (
                    "edli_admin_charges_pct",
                    models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
                ),
                (
                    "wage_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=15000.0,
                        help_text="Statutory wage ceiling for PF eligibility",
                        max_digits=15,
                    ),
                ),
                (
                    "eps_max_pensionable_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=15000.0,
                        help_text="Max salary considered for EPS pension calculation",
                        max_digits=15,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "PF Configuration",
                "verbose_name_plural": "PF Configurations",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalTaxSlab",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("salary_from", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "salary_to",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Professional Tax Slab",
                "verbose_name_plural": "Professional Tax Slabs",
                "ordering": ["state", "salary_from"],
            },
        ),
        migrations.CreateModel(
            name="TDSConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9, unique=True)),
                ("enable_old_regime", models.BooleanField(default=True)),
                ("enable_new_regime", models.BooleanField(default=True)),
                ("old_regime_slabs", models.JSONField(blank=True, default=dict)),
                ("new_regime_slabs", models.JSONField(blank=True, default=dict)),
                (
                    "standard_deduction_old",
                    models.DecimalField(
                        decimal_places=2, default=50000.0, max_digits=15
                    ),
                ),
                (
                    "standard_deduction_new",
                    models.DecimalField(
                        decimal_places=2, default=75000.0, max_digits=15
                    ),
                ),
                (
                    "education_cess_pct",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TDS Configuration",
                "verbose_name_plural": "TDS Configurations",
            },
        ),
        migrations.CreateModel(
            name="ComplianceCalendarEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("PF", "Provident Fund"),
                            ("ESI", "Employee State Insurance"),
                            ("PT", "Professional Tax"),
                            ("TDS", "TDS"),
                            ("LWF", "Labour Welfare Fund"),
                            ("GRATUITY", "Gratuity"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("period_year", models.IntegerField()),
                (
                    "period_quarter",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "period_half",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Challan/Return reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Calendar",
                "verbose_name_plural": "Compliance Calendar",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="GratuityCalculation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("date_of_exit", models.DateField()),
                (
                    "years_of_service",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_eligible", models.BooleanField(default=False)),
                (
                    "last_drawn_basic_da",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "gratuity_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_provision_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly provision set aside",
                        max_digits=15,
                    ),
                ),
                ("calculated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gratuity_calculations",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gratuity Calculation",
                "verbose_name_plural": "Gratuity Calculations",
            },
        ),
        migrations.CreateModel(
            name="BonusCalculation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "eligible_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salary considered for bonus calculation",
                        max_digits=15,
                    ),
                ),
                (
                    "bonus_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("payout_date", models.DateField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_calculations",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus Calculation",
                "verbose_name_plural": "Bonus Calculations",
                "unique_together": {("employee", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="ESIContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ip_number",
                    models.CharField(
                        blank=True,
                        help_text="Insured Person Number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_challan_generated", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esi_contributions",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esi_contributions",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESI Contribution",
                "verbose_name_plural": "ESI Contributions",
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="InvestmentDeclaration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[("OLD", "Old Regime"), ("NEW", "New Regime")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "section_80c_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "section_80d_self_family",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "section_80d_parents",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "section_80g_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "hra_rent_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "lta_claimed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "home_loan_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "nps_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True, null=True, upload_to="investment_proofs/%Y/%m/"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_declarations",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Declaration",
                "verbose_name_plural": "Investment Declarations",
                "unique_together": {("employee", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="PFContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "basic_da",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basic + DA for the month",
                        max_digits=15,
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "employee_pf",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employer_epf",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employer_eps",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employer_edli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employer_admin_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "edli_admin_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("uan", models.CharField(blank=True, max_length=12, null=True)),
                ("is_ecr_generated", models.BooleanField(default=False)),
                (
                    "ecr_file",
                    models.FileField(blank=True, null=True, upload_to="pf_ecr/%Y/%m/"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_contributions",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_contributions",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "PF Contribution",
                "verbose_name_plural": "PF Contributions",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="PTContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "pt_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("state", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_contributions",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_contributions",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "PT Deduction",
                "verbose_name_plural": "PT Deductions",
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="TDSCalculation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[("OLD", "Old Regime"), ("NEW", "New Regime")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "ytd_gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_exemptions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_standard_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_deductions_80c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_taxable_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_cess",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ytd_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_month_tds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tds_calculations",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tds_calculations",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "TDS Calculation",
                "verbose_name_plural": "TDS Calculations",
                "unique_together": {("employee", "financial_year", "month")},
            },
        ),
    ]
