# Generated by Django 5.2.12 on 2026-06-01 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_bonusconfiguration_esiconfiguration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compliancecalendarentry",
            options={
                "ordering": ["due_date"],
                "verbose_name": "Compliance Calendar",
                "verbose_name_plural": "Compliance Calendar Entries",
            },
        ),
    ]
