# Generated by Django 6.0.6 on 2026-06-26 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_transfer_history_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('adjustment_number', models.CharField(db_index=True, max_length=100)),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Stock Increase'), ('DECREASE', 'Stock Decrease')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorylocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventoryadjustment')),
            ],
            options={
                'verbose_name': 'Adjustment Attachment',
                'verbose_name_plural': 'Adjustment Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Current available stock at time of adjustment', max_digits=20, null=True)),
                ('adjustment_quantity', models.DecimalField(decimal_places=4, help_text='Positive = increase, Negative = decrease', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_items', to='inventory.inventoryitem')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_items', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Adjustment Line Item',
                'verbose_name_plural': 'Adjustment Line Items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reason_code', models.CharField(db_index=True, max_length=100)),
                ('reason_name', models.CharField(max_length=255)),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Stock Increase'), ('DECREASE', 'Stock Decrease')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-seeded system reason')),
            ],
            options={
                'verbose_name': 'Adjustment Reason',
                'verbose_name_plural': 'Adjustment Reasons',
                'ordering': ['reason_name'],
                'indexes': [models.Index(fields=['tenant_id', 'reason_code'], name='inventory_i_tenant__1ff27c_idx'), models.Index(fields=['tenant_id', 'adjustment_type'], name='inventory_i_tenant__4ac225_idx'), models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__26f90c_idx')],
                'unique_together': {('tenant_id', 'reason_code')},
            },
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventoryadjustmentreason'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Adjustment Created'), ('UPDATED', 'Adjustment Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventoryadjustment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment History Entry',
                'verbose_name_plural': 'Adjustment History Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['adjustment', 'timestamp'], name='inventory_i_adjustm_16a90f_idx'), models.Index(fields=['action'], name='inventory_i_action_55528a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant_id', 'adjustment_number'], name='inventory_i_tenant__a445e8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__f2bdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant_id', 'location'], name='inventory_i_tenant__38f2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant_id', 'adjustment_type'], name='inventory_i_tenant__63d9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant_id', 'adjustment_date'], name='inventory_i_tenant__f4e165_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryadjustment',
            unique_together={('tenant_id', 'adjustment_number')},
        ),
    ]
