# Generated by Django — seed default adjustment reasons

from django.db import migrations


SEED_REASONS = [
    {
        'reason_code': 'DAMAGE',
        'reason_name': 'Damage',
        'adjustment_type': 'DECREASE',
        'description': 'Stock damaged and no longer usable',
    },
    {
        'reason_code': 'LOSS',
        'reason_name': 'Loss',
        'adjustment_type': 'DECREASE',
        'description': 'Stock lost or missing',
    },
    {
        'reason_code': 'THEFT',
        'reason_name': 'Theft',
        'adjustment_type': 'DECREASE',
        'description': 'Stock stolen',
    },
    {
        'reason_code': 'EXPIRED',
        'reason_name': 'Expired',
        'adjustment_type': 'DECREASE',
        'description': 'Stock expired and cannot be used',
    },
    {
        'reason_code': 'CONSUMPTION',
        'reason_name': 'Consumption',
        'adjustment_type': 'DECREASE',
        'description': 'Stock consumed internally',
    },
    {
        'reason_code': 'PHYSICAL_COUNT_DIFF',
        'reason_name': 'Physical Count Difference',
        'adjustment_type': 'INCREASE',
        'description': 'Difference found during physical inventory count',
    },
    {
        'reason_code': 'INITIAL_CORRECTION',
        'reason_name': 'Initial Correction',
        'adjustment_type': 'INCREASE',
        'description': 'Initial stock setup correction',
    },
    {
        'reason_code': 'SYSTEM_CORRECTION',
        'reason_name': 'System Correction',
        'adjustment_type': 'INCREASE',
        'description': 'System-driven stock correction',
    },
]


def seed_adjustment_reasons(apps, schema_editor):
    InventoryAdjustmentReason = apps.get_model('inventory', 'InventoryAdjustmentReason')
    for reason_data in SEED_REASONS:
        InventoryAdjustmentReason.objects.update_or_create(
            reason_code=reason_data['reason_code'],
            defaults={
                'reason_name': reason_data['reason_name'],
                'adjustment_type': reason_data['adjustment_type'],
                'description': reason_data['description'],
                'status': 'ACTIVE',
                'is_default': True,
                'tenant_id': '00000000-0000-0000-0000-000000000000',  # Global default
            },
        )


def reverse_seed(apps, schema_editor):
    InventoryAdjustmentReason = apps.get_model('inventory', 'InventoryAdjustmentReason')
    InventoryAdjustmentReason.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_adjustment_models'),
    ]

    operations = [
        migrations.RunPython(seed_adjustment_reasons, reverse_seed),
    ]
