# Generated by Django 6.0.6 on 2026-06-26 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_seed_adjustment_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reservation_number', models.CharField(db_index=True, max_length=100)),
                ('reservation_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reservation_type', models.CharField(choices=[('SALES_ORDER', 'Sales Order'), ('TRANSFER', 'Transfer'), ('PRODUCTION', 'Production'), ('INTERNAL', 'Internal Use'), ('CUSTOMER', 'Customer Reservation'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventorylocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventoryreservation')),
            ],
            options={
                'verbose_name': 'Reservation Attachment',
                'verbose_name_plural': 'Reservation Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='inventory.inventoryitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryreservation')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_items', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Reservation Line Item',
                'verbose_name_plural': 'Reservation Line Items',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservationReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reason_code', models.CharField(db_index=True, max_length=100)),
                ('reason_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-seeded system reason')),
            ],
            options={
                'verbose_name': 'Reservation Reason',
                'verbose_name_plural': 'Reservation Reasons',
                'ordering': ['reason_name'],
                'indexes': [models.Index(fields=['tenant_id', 'reason_code'], name='inventory_i_tenant__acb1d5_idx'), models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__8f6e88_idx')],
                'unique_together': {('tenant_id', 'reason_code')},
            },
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryreservationreason'),
        ),
        migrations.CreateModel(
            name='InventoryReservationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Reservation Created'), ('UPDATED', 'Reservation Updated'), ('ACTIVATED', 'Reservation Activated'), ('FULFILLED', 'Reservation Fulfilled'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('CANCELLED', 'Reservation Cancelled'), ('EXPIRED', 'Reservation Expired')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_history_entries', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventoryreservation')),
            ],
            options={
                'verbose_name': 'Reservation History Entry',
                'verbose_name_plural': 'Reservation History Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['reservation', 'timestamp'], name='inventory_i_reserva_265f56_idx'), models.Index(fields=['action'], name='inventory_i_action_3c4dc3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'reservation_number'], name='inventory_i_tenant__fdbb00_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__b72c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'source_location'], name='inventory_i_tenant__60ff37_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'reservation_date'], name='inventory_i_tenant__a12dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'expiry_date'], name='inventory_i_tenant__6c452e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['tenant_id', 'reservation_type'], name='inventory_i_tenant__1113ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryreservation',
            unique_together={('tenant_id', 'reservation_number')},
        ),
    ]
