# Generated by Django 6.0.6 on 2026-07-11 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryreservation_inventoryreservationattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('count_number', models.CharField(db_index=True, max_length=100)),
                ('count_date', models.DateField()),
                ('count_type', models.CharField(choices=[('FULL', 'Full Count'), ('CYCLE', 'Cycle Count'), ('SPOT', 'Spot Check'), ('ANNUAL', 'Annual Physical Count')], default='CYCLE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items_counted', models.PositiveIntegerField(default=0)),
                ('total_items_with_difference', models.PositiveIntegerField(default=0)),
                ('total_difference_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('assigned_counters', models.ManyToManyField(blank=True, help_text='Users assigned to perform the physical count', related_name='assigned_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Optional — if set, only items in this category are counted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='inventory.itemcategory')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('generated_adjustment', models.ForeignKey(blank=True, help_text='Adjustment auto-generated from count differences', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_stock_counts', to='inventory.inventoryadjustment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.inventorylocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physical Stock Count',
                'verbose_name_plural': 'Physical Stock Counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockCountAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorystockcount')),
            ],
            options={
                'verbose_name': 'Stock Count Attachment',
                'verbose_name_plural': 'Stock Count Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reason_code', models.CharField(db_index=True, max_length=100)),
                ('reason_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-seeded system reason')),
            ],
            options={
                'verbose_name': 'Stock Count Reason',
                'verbose_name_plural': 'Stock Count Reasons',
                'ordering': ['reason_name'],
                'indexes': [models.Index(fields=['tenant_id', 'reason_code'], name='inventory_s_tenant__e464a4_idx'), models.Index(fields=['tenant_id', 'status'], name='inventory_s_tenant__5fdf8d_idx')],
                'unique_together': {('tenant_id', 'reason_code')},
            },
        ),
        migrations.AddField(
            model_name='inventorystockcount',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.stockcountreason'),
        ),
        migrations.CreateModel(
            name='InventoryStockCountHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Count Created'), ('UPDATED', 'Count Updated'), ('ASSIGNED', 'Counters Assigned'), ('STARTED', 'Counting Started'), ('ITEM_COUNTED', 'Item Counted'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ADJUSTMENT_GENERATED', 'Adjustment Generated')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorystockcount')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Count History Entry',
                'verbose_name_plural': 'Stock Count History Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['count', 'timestamp'], name='inventory_i_count_i_a80fc0_idx'), models.Index(fields=['action'], name='inventory_i_action_ad3202_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=0, help_text='System quantity at time count was created (from Stock Ledger)', max_digits=20)),
                ('reserved_quantity_at_count', models.DecimalField(decimal_places=4, default=0, help_text='Reserved stock at time count was created', max_digits=20)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Actual physical quantity counted (null = not yet counted)', max_digits=20, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_barcode', models.CharField(blank=True, help_text='Barcode scanned during counting (if applicable)', max_length=255)),
                ('difference_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Difference = counted - expected. Positive = surplus, Negative = shortage', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorystockcount')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_items', to='inventory.inventoryitem')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_items', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Stock Count Line Item',
                'verbose_name_plural': 'Stock Count Line Items',
                'indexes': [models.Index(fields=['count', 'item'], name='inventory_i_count_i_225d7f_idx'), models.Index(fields=['item'], name='inventory_i_item_id_17bc54_idx')],
                'unique_together': {('count', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='inventorystockcount',
            index=models.Index(fields=['tenant_id', 'count_number'], name='inventory_i_tenant__752581_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockcount',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__a10732_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockcount',
            index=models.Index(fields=['tenant_id', 'location'], name='inventory_i_tenant__dc69ab_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockcount',
            index=models.Index(fields=['tenant_id', 'count_date'], name='inventory_i_tenant__bc07b7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockcount',
            index=models.Index(fields=['tenant_id', 'count_type'], name='inventory_i_tenant__031a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystockcount',
            unique_together={('tenant_id', 'count_number')},
        ),
    ]
