# Generated by Django 6.0.6 on 2026-07-11 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
        ('inventory', '0011_physical_stock_count_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_IN', 'Purchase In'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('order_number', models.CharField(db_index=True, max_length=100)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Denormalized supplier name for display', max_length=500)),
                ('supplier_reference', models.CharField(blank=True, help_text='Supplier reference number on their PO', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.inventorylocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Attachment',
                'verbose_name_plural': 'Purchase Order Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'PO Created'), ('UPDATED', 'PO Updated'), ('SENT', 'Sent to Supplier'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_history_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order History Entry',
                'verbose_name_plural': 'Purchase Order History Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate in percentage (e.g. 10.00 for 10%%)', max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=4, default=0, help_text='Discount rate in percentage (e.g. 5.00 for 5%%)', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, help_text='Calculated: (qty * unit_price) * (1 + tax_rate/100) * (1 - discount_rate/100)', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('receipt_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.inventorylocation')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Receipt',
                'verbose_name_plural': 'Purchase Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='inventory.inventoryitem')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.purchaseorderitem')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereceipt')),
            ],
            options={
                'verbose_name': 'Purchase Receipt Item',
                'verbose_name_plural': 'Purchase Receipt Items',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'order_number'], name='inventory_p_tenant__6d8ece_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_p_tenant__909421_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'supplier'], name='inventory_p_tenant__da9b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'location'], name='inventory_p_tenant__b5998e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'order_date'], name='inventory_p_tenant__68f725_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant_id', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderhistory',
            index=models.Index(fields=['purchase_order', 'timestamp'], name='inventory_p_purchas_2748f9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderhistory',
            index=models.Index(fields=['action'], name='inventory_p_action_3453eb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'item'], name='inventory_p_purchas_aeca13_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['tenant_id', 'receipt_number'], name='inventory_p_tenant__42beb6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['tenant_id', 'purchase_order'], name='inventory_p_tenant__930c64_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['tenant_id', 'receipt_date'], name='inventory_p_tenant__055a3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasereceipt',
            unique_together={('tenant_id', 'receipt_number')},
        ),
    ]
