# Generated by Django 6.0.6 on 2026-07-12 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
        ('inventory', '0012_purchase_management_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_IN', 'Purchase In'), ('GOODS_RECEIPT', 'Goods Receipt'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryGoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('grn_number', models.CharField(db_index=True, max_length=100)),
                ('receipt_date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, help_text='Denormalized supplier name for display', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grns', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_grns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.inventorylocation')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goods Receipt Note',
                'verbose_name_plural': 'Goods Receipt Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryGoodsReceiptAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorygoodsreceipt')),
            ],
            options={
                'verbose_name': 'GRN Attachment',
                'verbose_name_plural': 'GRN Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryGoodsReceiptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'GRN Created'), ('UPDATED', 'GRN Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorygoodsreceipt')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GRN History Entry',
                'verbose_name_plural': 'GRN History Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryGoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity ordered on the PO', max_digits=20)),
                ('received_quantity', models.DecimalField(decimal_places=4, help_text='Total quantity received', max_digits=20)),
                ('accepted_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity accepted (good condition)', max_digits=20)),
                ('rejected_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity rejected (quality issues)', max_digits=20)),
                ('damage_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity damaged in transit', max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorygoodsreceipt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='inventory.inventoryitem')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='inventory.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'GRN Line Item',
                'verbose_name_plural': 'GRN Line Items',
            },
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'grn_number'], name='inventory_i_tenant__923a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__ed0ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'purchase_order'], name='inventory_i_tenant__50c405_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'supplier'], name='inventory_i_tenant__b3ef13_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'location'], name='inventory_i_tenant__f6c8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipt',
            index=models.Index(fields=['tenant_id', 'receipt_date'], name='inventory_i_tenant__7219d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorygoodsreceipt',
            unique_together={('tenant_id', 'grn_number')},
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipthistory',
            index=models.Index(fields=['goods_receipt', 'timestamp'], name='inventory_i_goods_r_d32e47_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceipthistory',
            index=models.Index(fields=['action'], name='inventory_i_action_6a8aca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorygoodsreceiptitem',
            index=models.Index(fields=['goods_receipt', 'item'], name='inventory_i_goods_r_bd6395_idx'),
        ),
    ]
