# Generated by Django 6.0.6 on 2026-07-12 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
        ('inventory', '0013_alter_stockledger_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Denormalized supplier name for display', max_length=500)),
                ('supplier_invoice_number', models.CharField(blank=True, help_text="Vendor's invoice reference number", max_length=200)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate from invoice currency to base currency', max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], default='DRAFT', max_length=30)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('shipping_charges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_charges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('goods_receipts', models.ManyToManyField(blank=True, help_text='Goods Receipt Notes covered by this invoice', related_name='supplier_invoices', to='inventory.inventorygoodsreceipt')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierInvoiceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorysupplierinvoice')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Attachment',
                'verbose_name_plural': 'Supplier Invoice Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierInvoiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Invoice Created'), ('UPDATED', 'Invoice Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorysupplierinvoice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Invoice History Entry',
                'verbose_name_plural': 'Supplier Invoice History Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_description', models.CharField(blank=True, help_text='Description of the item/service', max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate in percentage (e.g. 18.00 for 18%%)', max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=4, default=0, help_text='Discount rate in percentage (e.g. 5.00 for 5%%)', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, help_text='Calculated: (qty * unit_price) * (1 + tax_rate/100) * (1 - discount_rate/100)', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('goods_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='inventory.inventorygoodsreceiptitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysupplierinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Line Item',
                'verbose_name_plural': 'Supplier Invoice Line Items',
            },
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'invoice_number'], name='inventory_i_tenant__879aee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__ad990b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'payment_status'], name='inventory_i_tenant__6dfc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'supplier'], name='inventory_i_tenant__19164e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'purchase_order'], name='inventory_i_tenant__1c92a7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'invoice_date'], name='inventory_i_tenant__866e23_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoice',
            index=models.Index(fields=['tenant_id', 'due_date'], name='inventory_i_tenant__29e647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysupplierinvoice',
            unique_together={('tenant_id', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoicehistory',
            index=models.Index(fields=['invoice', 'timestamp'], name='inventory_i_invoice_361cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoicehistory',
            index=models.Index(fields=['action'], name='inventory_i_action_5f5ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierinvoiceitem',
            index=models.Index(fields=['invoice', 'item'], name='inventory_i_invoice_da666f_idx'),
        ),
    ]
