# Generated by Django 5.2.12 on 2026-07-12 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
        ('inventory', '0014_inventorysupplierinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorygoodsreceiptitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total quantity returned to supplier', max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_IN', 'Purchase In'), ('GOODS_RECEIPT', 'Goods Receipt'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryPurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('return_number', models.CharField(db_index=True, max_length=100)),
                ('return_date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, help_text='Denormalized supplier name for display', max_length=500)),
                ('return_reason', models.CharField(blank=True, help_text='Reason for returning goods', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.inventorygoodsreceipt')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='contacts.contact')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.inventorysupplierinvoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchaseReturnAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorypurchasereturn')),
            ],
            options={
                'verbose_name': 'Purchase Return Attachment',
                'verbose_name_plural': 'Purchase Return Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchaseReturnHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Return Created'), ('UPDATED', 'Return Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to Supplier'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_history_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorypurchasereturn')),
            ],
            options={
                'verbose_name': 'Purchase Return History Entry',
                'verbose_name_plural': 'Purchase Return History Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Original received quantity for reference', max_digits=20)),
                ('return_quantity', models.DecimalField(decimal_places=4, help_text='Quantity being returned', max_digits=20)),
                ('damaged_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Of the returned qty, how much is damaged', max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate in percentage', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, help_text='Calculated: (return_qty * unit_cost) * (1 + tax_rate/100)', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('goods_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_items', to='inventory.inventorygoodsreceiptitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.inventoryitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorypurchasereturn')),
            ],
            options={
                'verbose_name': 'Purchase Return Line Item',
                'verbose_name_plural': 'Purchase Return Line Items',
            },
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'return_number'], name='inventory_i_tenant__7b5395_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__568e89_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'supplier'], name='inventory_i_tenant__191703_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'goods_receipt'], name='inventory_i_tenant__303bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'supplier_invoice'], name='inventory_i_tenant__f8a5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturn',
            index=models.Index(fields=['tenant_id', 'return_date'], name='inventory_i_tenant__1acfab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorypurchasereturn',
            unique_together={('tenant_id', 'return_number')},
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturnhistory',
            index=models.Index(fields=['purchase_return', 'timestamp'], name='inventory_i_purchas_2db425_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturnhistory',
            index=models.Index(fields=['action'], name='inventory_i_action_c2a4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchasereturnitem',
            index=models.Index(fields=['purchase_return', 'item'], name='inventory_i_purchas_bdd3e0_idx'),
        ),
    ]
