# Generated by Django 5.2.12 on 2026-07-12 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
        ('inventory', '0015_purchase_return_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('payment_number', models.CharField(db_index=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, help_text='Denormalized supplier name', max_length=500)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking'), ('DD', 'Demand Draft'), ('Other', 'Other')], default='Bank Transfer', max_length=30)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account or payment source reference', max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number, transaction ID, UPI ref, etc.', max_length=200)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('allocated_amount', models.DecimalField(decimal_places=4, default=0, help_text='Amount allocated to specific invoices', max_digits=20)),
                ('unallocated_amount', models.DecimalField(decimal_places=4, default=0, help_text='Unallocated / advance amount', max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], default='DRAFT', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=4, help_text='Amount allocated to this invoice', max_digits=20)),
                ('remarks', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.inventorysupplierpayment')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='inventory.inventorysupplierinvoice')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierPaymentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorysupplierpayment')),
            ],
            options={
                'verbose_name': 'Supplier Payment Attachment',
                'verbose_name_plural': 'Supplier Payment Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierPaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Payment Created'), ('UPDATED', 'Payment Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorysupplierpayment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payment_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment History Entry',
                'verbose_name_plural': 'Supplier Payment History Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpayment',
            index=models.Index(fields=['tenant_id', 'payment_number'], name='inventory_i_tenant__8c950c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpayment',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__b6e33e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpayment',
            index=models.Index(fields=['tenant_id', 'supplier'], name='inventory_i_tenant__711d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpayment',
            index=models.Index(fields=['tenant_id', 'payment_date'], name='inventory_i_tenant__1ee8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpayment',
            index=models.Index(fields=['tenant_id', 'payment_method'], name='inventory_i_tenant__93375b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysupplierpayment',
            unique_together={('tenant_id', 'payment_number')},
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpaymentallocation',
            index=models.Index(fields=['payment', 'supplier_invoice'], name='inventory_i_payment_b4be2b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpaymentallocation',
            index=models.Index(fields=['supplier_invoice'], name='inventory_i_supplie_4e79ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysupplierpaymentallocation',
            unique_together={('payment', 'supplier_invoice')},
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpaymenthistory',
            index=models.Index(fields=['payment', 'timestamp'], name='inventory_i_payment_c3c7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysupplierpaymenthistory',
            index=models.Index(fields=['action'], name='inventory_i_action_f8df15_idx'),
        ),
    ]
