# Generated by Django 6.0.6 on 2026-07-12 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_supplier_payment_models'),
        ('menus', '0004_remove_menuuser_unique_menu_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique feature code: 'dashboard', 'items', 'stock', etc.", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Display name: 'Dashboard', 'Items', 'Stock Availability'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name: 'LayoutDashboard', 'Box', etc.", max_length=100)),
                ('route', models.CharField(blank=True, help_text="Frontend route path: '/inventory/dashboard', '/inventory/items'", max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Globally active')),
            ],
            options={
                'verbose_name': 'Inventory Feature',
                'verbose_name_plural': 'Inventory Features',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='inventory_i_code_52cb61_idx'), models.Index(fields=['is_active'], name='inventory_i_is_acti_66e3cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyInventoryFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_feature_configs', to='menus.organization')),
                ('inventory_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_configs', to='inventory.inventoryfeature')),
            ],
            options={
                'verbose_name': 'Company Inventory Feature',
                'verbose_name_plural': 'Company Inventory Feature Configs',
                'indexes': [models.Index(fields=['company', 'enabled'], name='inventory_c_company_db9df0_idx'), models.Index(fields=['company', 'inventory_feature'], name='inventory_c_company_45e83b_idx')],
                'unique_together': {('company', 'inventory_feature')},
            },
        ),
    ]
