# Generated by Django 6.0.6 on 2026-06-16 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediacollection',
            name='unique_collection_name_per_user',
        ),
        migrations.AddConstraint(
            model_name='mediacollection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'created_by'), name='unique_collection_name_per_user'),
        ),
    ]
