# Generated by Django 6.0.6 on 2026-06-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0005_add_unique_constraint_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='source_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the source entity (Contact, Employee, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_display',
            field=models.CharField(blank=True, help_text="Human-readable label like 'Contact: John Doe (CUS-001)'", max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_object_id',
            field=models.CharField(blank=True, help_text='Primary key of the source entity', max_length=255),
        ),
    ]
