# Generated by Django 6.0.6 on 2026-06-20 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
        ('media', '0006_mediaasset_source_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollectionGroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='media.mediacollection')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_collection_permissions', to='authentication.department')),
            ],
            options={
                'verbose_name': 'Media Collection Group Permission',
                'verbose_name_plural': 'Media Collection Group Permissions',
                'ordering': ['collection', 'department'],
                'indexes': [models.Index(fields=['collection'], name='media_media_collect_e369e9_idx'), models.Index(fields=['department'], name='media_media_departm_6bc3d5_idx')],
                'unique_together': {('collection', 'department')},
            },
        ),
    ]
