# Generated by Django 6.0.6 on 2026-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_add_collection_group_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacollection',
            name='entity_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('contact', 'Contact'), ('staff', 'Staff')], default='generic', help_text="Type of entity this collection's assets map to (Generic, Contact, or Staff)", max_length=20),
        ),
    ]
