# Generated by Django 6.0.6 on 2026-06-20 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
        ('media', '0008_add_entity_type_to_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCreatorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_creator_permissions', to='authentication.department', unique=True)),
            ],
            options={
                'verbose_name': 'Media Creator Group',
                'verbose_name_plural': 'Media Creator Groups',
                'ordering': ['department__name'],
            },
        ),
    ]
