# Generated by Django 6.0.7 on 2026-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_mediacollectiongrouppermission_mediacreatorgroup_and_more'),
        ('media', '0009_add_creator_group_model'),
    ]

    operations = [
    ]
