# Generated by Django 6.0.7 on 2026-07-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
        ('media', '0010_merge_20260719_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacreatorgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_creator_permissions', to='authentication.department', unique=True),
        ),
    ]
